name: "Build and Publish"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up JDK"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: "Grant execute permission for Gradle"
        run: chmod +x gradlew

      - name: "Build with Gradle"
        run: ./gradlew build

      - name: "Upload Release Asset"
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/Portalify-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
